application: showtownmvp
version: 10
runtime: python27
api_version: 1
threadsafe: yes



handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /javascript
  static_dir: javascript
  
- url: /admin.*
  script: admin.app
  login: admin
 

- url: /taskslist.*
  script: cron.app

- url: /signup.*
  script: signup.app
  
- url: /(.*?)_profile.*
  script: profile.app
  
- url: /(.*?)_gig.*
  script: gigs.app
  
- url: /login_handler.*
  script: login.app
  
- url: /logout_handler.*
  script: logout.app

- url: /video.*
  script: video_handler.app
  
- url: /venue.*
  script: venues.app
 
- url: /imgs.*
  script: image_handler.app
  
- url: /vote.*
  script: vote_handler.app

  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
  
- name: numpy
  version: latest
